// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikenkhjrindacsufnhsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZW5raGpyaW5kYWNzdWZuaHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTQxNTgsImV4cCI6MjA3MTEzMDE1OH0.2gf2OxjUFdspDyBH2yClN55HlqXQMIquHVlL5W7-wMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});